[11.0][ADD] cet_website_sale: login invite & shop/product page text
coopiteasy/cycle-en-terre pull request #69
Opened 2020-04-06 13:54 UTC by vvrossem

## [Tâche](https://gestion.coopiteasy.be/web#id=4215&view_type=form&model=project.task&action=475&active_id=97)

### Ajout:
- d'un texte invitant les clients à se connecter avant de remplir leur panier
- d'un texte sous le menu mois de semi sur la page de la boutique
- du **même** texte sous le menu des catégories sur la page Articles

**Backend**
* _Configuration des messages_
![cet-settings](https://user-images.githubusercontent.com/28013700/78564445-bb005500-781c-11ea-850c-3c715f318c8f.png)

**Frontend**
* _Invitation à se connecter & texte sur la page `/shop`_
![cet-login-invite-custom-text](https://user-images.githubusercontent.com/28013700/78565181-d029b380-781d-11ea-98c6-7df202fae1c6.png)

* _Texte sous le menu des catégories sur la page `/shop/product/un-produit`_
![cet-custom-text](https://user-images.githubusercontent.com/28013700/78565246-ea639180-781d-11ea-9a21-4d7906dcb8f1.png)

### Problème connu: 
- Backend: agrandir la largeur des champs .Html
- Frontend: remplacer l'invitation à se connecter par un popup

2020-04-07 08:46 UTC, remytms requested changes

2020-04-07 08:46 UTC, remytms commented on cet_website_sale/views/res_config_settings_views.xml
> +                    <div class="col-xs-12 col-md-6 o_setting_box" id="custom_login">
Pour que le texte à éditer soit plus large, change juste ici: `col-md-6` -> `col-md-12`.

2020-04-07 08:46 UTC, remytms commented on cet_website_sale/views/res_config_settings_views.xml
> +                    <div class="col-xs-12 col-md-6 o_setting_box" id="custom_text">
Idem que le commentaire précédent.

2020-04-07 08:46 UTC, remytms commented on cet_website_sale/views/website_sale_templates.xml
> +<!-- Copyright 2020 Coop IT Easy SCRLfs
Je pense qu'il faut laisser la date d'origine et mettre 2018-2020.

2020-04-07 08:46 UTC, remytms commented on cet_website_sale/views/website_sale_templates.xml
> +      </div>
Ça dépend avec quoi on veut aligner le texte ajouté, mais si on veut l'aligner avec ce qui suit, je pense qu'il faut faire ceci:
```html
<div class="row">
    <div class="col-xs-12">
        <span t-raw="request.website.custom_text"/>
    </div>
</div>
```

2020-04-07 08:46 UTC, remytms commented on cet_website_sale/views/website_sale_templates.xml
> +      </div>
Il y a une raison pour laquel, le "custom text" n'est pas ajouté via un xpath avec son propre template comme aux autre endroits ?

2020-04-07 08:46 UTC, remytms commented on cet_website_sale/views/website_sale_templates.xml
> +            <span t-raw="request.website.login_invite"/>
Ce serait une bonne idée de l'encapsulé dans un `row` puis dans un `col`, histoire de marge. :)

2020-04-07 08:46 UTC, remytms commented on cet_website_sale/views/website_sale_templates.xml
> +        </div>
Même remarque avec l'histoire des `col` dans les `row`. :)

2020-04-07 08:46 UTC, remytms commented on cet_website_sale/views/website_sale_templates.xml
> +          priority="1">
Je n'ai pas été voir plus loin, mais, la priorité par défaut, je pense que c'est 20. Donc si tu veux que "custom login invite" soit chargé après "custom text", essaie plutôt de mettre `priority=30` pour "login invite". Ça laisse plus de flexibilité pour ajouter des choses plus prioritaires dans le future.

2020-04-07 08:47 UTC, remytms commented
Tes PR sont juste magique !

2020-04-07 14:12 UTC, vvrossem commented on cet_website_sale/views/res_config_settings_views.xml
> +                    <div class="col-xs-12 col-md-6 o_setting_box" id="custom_login">
done

2020-04-07 14:12 UTC, vvrossem commented on cet_website_sale/views/res_config_settings_views.xml
> +                    <div class="col-xs-12 col-md-6 o_setting_box" id="custom_text">
done

2020-04-07 14:12 UTC, vvrossem commented on cet_website_sale/views/website_sale_templates.xml
> +<!-- Copyright 2020 Coop IT Easy SCRLfs
done

2020-04-07 14:12 UTC, vvrossem commented on cet_website_sale/views/website_sale_templates.xml
> +      </div>
pas de bonne raison -> placé dans son propre template

2020-04-07 14:12 UTC, vvrossem commented on cet_website_sale/views/website_sale_templates.xml
> +            <span t-raw="request.website.login_invite"/>
done

2020-04-07 14:12 UTC, vvrossem commented on cet_website_sale/views/website_sale_templates.xml
> +        </div>
done

2020-04-07 14:12 UTC, vvrossem commented on cet_website_sale/views/website_sale_templates.xml
> +          priority="1">
done

2020-04-07 14:13 UTC, vvrossem commented
@remytms j'ai apporté les modifications demandées

2020-04-08 08:18 UTC, remytms approved these changes
Perfect. :)

2020-04-08 08:31 UTC, merged